In [ ]:
%cd /content/drive/MyDrive/FDFS_feb_Batch/NLP/Introduction_to_Transformers

/content/drive/MyDrive/FDFS_feb_Batch/NLP/Introduction_to_Transformers


In [ ]:
try:
  from transformers import pipeline
except Exception as e:
  print(e)
  print("installing...")
  !pip install datasets transformers[sentencepiece] -q
  from transformers import pipeline

No module named 'transformers'
installing...
     |████████████████████████████████| 362 kB 13.2 MB/s 
     |████████████████████████████████| 4.4 MB 43.8 MB/s 
     |████████████████████████████████| 101 kB 11.0 MB/s 
     |████████████████████████████████| 1.1 MB 47.9 MB/s 
     |████████████████████████████████| 140 kB 43.5 MB/s 
     |████████████████████████████████| 212 kB 42.4 MB/s 
     |████████████████████████████████| 596 kB 49.0 MB/s 
     |████████████████████████████████| 127 kB 53.8 MB/s 
     |████████████████████████████████| 94 kB 3.5 MB/s 
     |████████████████████████████████| 144 kB 59.2 MB/s 
     |████████████████████████████████| 271 kB 55.3 MB/s 
     |████████████████████████████████| 6.6 MB 41.6 MB/s 
     |████████████████████████████████| 1.2 MB 50.2 MB/s 
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
datascience 0.10.6 requires 

In [ ]:
model_name = "bert-base-cased"

- Checking token outputs with BertTokenizer and Autotokenizer

In [ ]:
from transformers import BertTokenizer, AutoTokenizer

In [ ]:
tokenizer = BertTokenizer.from_pretrained(model_name)
auto_tokenizer = AutoTokenizer.from_pretrained(model_name)

Downloading:   0%|          | 0.00/208k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/29.0 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/570 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/426k [00:00<?, ?B/s]

In [ ]:
example = "Transformer is an interesting library"

In [ ]:
tokenizer(example)

{'input_ids': [101, 13809, 23763, 1110, 1126, 5426, 3340, 102], 'token_type_ids': [0, 0, 0, 0, 0, 0, 0, 0], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1]}

In [ ]:
auto_tokenizer(example)

{'input_ids': [101, 13809, 23763, 1110, 1126, 5426, 3340, 102], 'token_type_ids': [0, 0, 0, 0, 0, 0, 0, 0], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1]}

we can observe both the output tokens are same, this is because we are using the same model("bert-base-cased")

In [ ]:
#saving the tokenizer
tokenizer.save_pretrained("./sample_tokenizer")

('./sample_tokenizer/tokenizer_config.json',
 './sample_tokenizer/special_tokens_map.json',
 './sample_tokenizer/vocab.txt',
 './sample_tokenizer/added_tokens.json')

In [ ]:
# Reloading the tokenizer
loaded_tokenizer = AutoTokenizer.from_pretrained("./sample_tokenizer")

In [ ]:
loaded_tokenizer(example)

{'input_ids': [101, 13809, 23763, 1110, 1126, 5426, 3340, 102], 'token_type_ids': [0, 0, 0, 0, 0, 0, 0, 0], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1]}

In [ ]:
# Reconverting tokens to sentence
auto_tokenizer.tokenize(example)

['Trans', '##former', 'is', 'an', 'interesting', 'library']

In [ ]:
tokens = tokenizer.tokenize(example)
tokens

['Trans', '##former', 'is', 'an', 'interesting', 'library']

In [ ]:
#  converting the above obtained tokens to ids
ids = tokenizer.convert_tokens_to_ids(tokens)
ids

[13809, 23763, 1110, 1126, 5426, 3340]

In [ ]:
tokenizer.convert_ids_to_tokens(ids)

['Trans', '##former', 'is', 'an', 'interesting', 'library']

In [ ]:
# appending start and end tokens ids to token list
updated_ids = [101, 13809, 23763, 1110, 1126, 5426, 3340, 102]

In [ ]:
tokenizer.convert_ids_to_tokens(updated_ids)


['[CLS]', 'Trans', '##former', 'is', 'an', 'interesting', 'library', '[SEP]']

In [ ]:
# adding random tokens at the end
updated_ids = [101, 13809, 23763, 1110, 1126, 5426, 3340, 102, 200, 200]

In [ ]:
tokenizer.convert_ids_to_tokens(updated_ids)


['[CLS]',
 'Trans',
 '##former',
 'is',
 'an',
 'interesting',
 'library',
 '[SEP]',
 '¡',
 '¡']

In [ ]:
updated_ids = [101, 13809, 23763, 1110, 1126, 5426, 3340, 102, 0, 0]

In [ ]:
tokenizer.convert_ids_to_tokens(updated_ids)


['[CLS]',
 'Trans',
 '##former',
 'is',
 'an',
 'interesting',
 'library',
 '[SEP]',
 '[PAD]',
 '[PAD]']

In [ ]:
tokenizer.decode(updated_ids)

'[CLS] Transformer is an interesting library [SEP] [PAD] [PAD]'

In [ ]:
tokenizer.decode(ids)

'Transformer is an interesting library'

## handling multiple sequences

In [ ]:
import torch
from transformers import AutoTokenizer, AutoModelForSequenceClassification

In [ ]:
ckpt = "distilbert-base-uncased-finetuned-sst-2-english"
tokenizer = AutoTokenizer.from_pretrained(ckpt)
model = AutoModelForSequenceClassification.from_pretrained(ckpt)

Downloading:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/629 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/226k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/255M [00:00<?, ?B/s]

In [ ]:
example = "I've been exploring Transformers for Natural Language Processing"

In [ ]:
tokens = tokenizer.tokenize(example)  # tokenizing the sentence, i.e. breaking into word tokens
ids = tokenizer.convert_tokens_to_ids(tokens) # converting word tokens into ids
input_ids = torch.tensor(ids) # coverting ids as a tensor

In [ ]:
tokens

['i',
 "'",
 've',
 'been',
 'exploring',
 'transformers',
 'for',
 'natural',
 'language',
 'processing']

In [ ]:
ids

[1045, 1005, 2310, 2042, 11131, 19081, 2005, 3019, 2653, 6364]

In [ ]:
input_ids

tensor([ 1045,  1005,  2310,  2042, 11131, 19081,  2005,  3019,  2653,  6364])

In [ ]:
model(input_ids)

IndexError: ignored

- for : **model(input_ids)**  we are trying to supply tensor_id directly to model.
- we have only got a one dimesional tensor, we will need a 2D tensor to pass the information.
- to convert **input_ids** to 2D we use torch.unsqueeze

In [ ]:
torch.unsqueeze(input_ids, dim=0)

tensor([[ 1045,  1005,  2310,  2042, 11131, 19081,  2005,  3019,  2653,  6364]])

In [ ]:
model(torch.unsqueeze(input_ids, dim=0))

SequenceClassifierOutput([('logits',
                           tensor([[ 1.0319, -0.8272]], grad_fn=<AddmmBackward0>))])

#### Aternately we can give "return_tensors = 'pt'"parameter in the tokenizer itself to get the pytorch tensors


In [ ]:
tokenized_inputs = tokenizer(example, return_tensors='pt')

In [ ]:
tokenized_inputs["input_ids"]

tensor([[  101,  1045,  1005,  2310,  2042, 11131, 19081,  2005,  3019,  2653,
          6364,   102]])

In [ ]:
model(tokenized_inputs["input_ids"])

SequenceClassifierOutput([('logits',
                           tensor([[-0.3594,  0.4591]], grad_fn=<AddmmBackward0>))])

notice that tensor outputs will be diffrent if we use unsqueeze method  and parmaeter in tokenizer method

#### Padding

In [ ]:
tokenizer.pad_token_id

0

In [ ]:
# padding variable length sentences
example_1 = "I've been exploring Transformers for Natural Language Processing."
example_2 = "I've been exploring Transformers."


In [ ]:
token_1 = tokenizer.tokenize(example_1)
print(token_1)
token_2 = tokenizer.tokenize(example_2)
print(token_2)

['i', "'", 've', 'been', 'exploring', 'transformers', 'for', 'natural', 'language', 'processing', '.']
['i', "'", 've', 'been', 'exploring', 'transformers', '.']


In [ ]:
id_1 = tokenizer.convert_tokens_to_ids(token_1)
id_2 = tokenizer.convert_tokens_to_ids(token_2)

In [ ]:
len(id_1)

11

In [ ]:
len(id_2)

7

In [ ]:
batch_id = [
            id_1,
            id_2
]
batch_id

[[1045, 1005, 2310, 2042, 11131, 19081, 2005, 3019, 2653, 6364, 1012],
 [1045, 1005, 2310, 2042, 11131, 19081, 1012]]

In [ ]:
model(torch.tensor([id_1])).logits

tensor([[ 0.9019, -0.6752]], grad_fn=<AddmmBackward0>)

In [ ]:
model(torch.tensor([id_2])).logits


tensor([[-0.5456,  0.7677]], grad_fn=<AddmmBackward0>)

In [ ]:
# pad sequence length must be same
model(torch.tensor(batch_id)).logits

ValueError: ignored

In [ ]:
batch_id_same_seq_len = [
            id_1,
            id_1
]

In [ ]:
model(torch.tensor(batch_id_same_seq_len)).logits

tensor([[ 0.9019, -0.6752],
        [ 0.9019, -0.6752]], grad_fn=<AddmmBackward0>)

In [ ]:
# pad max length to 11

max_len = 11

while  len(id_2)!= max_len:
  id_2.append(tokenizer.pad_token_id)

In [ ]:
len(id_2)

11

In [ ]:
id_2

[1045, 1005, 2310, 2042, 11131, 19081, 1012, 0, 0, 0, 0]

In [ ]:
batch_id = [
            id_1,
            id_2
]
batch_id

[[1045, 1005, 2310, 2042, 11131, 19081, 2005, 3019, 2653, 6364, 1012],
 [1045, 1005, 2310, 2042, 11131, 19081, 1012, 0, 0, 0, 0]]

In [ ]:
model(torch.tensor(batch_id)).logits

tensor([[ 0.9019, -0.6752],
        [ 0.7740, -0.6163]], grad_fn=<AddmmBackward0>)

creating an attention mask

In [ ]:
[1]*11

[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]

In [ ]:
([1]*7).extend([0,0,0,0])

In [ ]:
[1]*7 + [0]*4

[1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0]

In [ ]:
attention_mask = [
                  [1]*11,
                  [1]*7 + [0]*4
]
attention_mask

[[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0]]

In [ ]:
model(
    torch.tensor(batch_id),
    attention_mask=torch.tensor(attention_mask)
    ).logits

tensor([[ 0.9019, -0.6752],
        [-0.5456,  0.7677]], grad_fn=<AddmmBackward0>)

In [ ]:
512, 1024, truncation